### ISSUE TITLE
Trocar a logomarca do governo federal das telas da aplicação

### ISSUE THREAD

**Issue by joseroberto** [rdemorais/ecar-spa#1]
Trocar a logomarca do governo federal das telas da aplicação

**Comment by paulohbalmeida** [comment]
![marca-fonte-escura-transparente](https://cloud.githubusercontent.com/assets/11232884/15078856/a7cdc8d6-138b-11e6-829c-a31fde9ad80e.png)

**Comment by rdemorais** [comment]
PH, 

Eu preciso dela transparente nos mesmos moldes da que está lá atualmente.

**Comment by paulohbalmeida** [comment]
Rafa, pode trocar por esta com o texto em branco!
![marca-fonte-branca-transparente](https://cloud.githubusercontent.com/assets/11232884/15081476/9271c88a-1399-11e6-9056-f909d290aa7a.png)
