### ISSUE TITLE
Trocar marca de governo

### ISSUE THREAD

**Issue by paulohbalmeida** [rdemorais/ecar-spa#12]
Rafa, segue a logo vazada em branco do SUS e ministério para o PEMS.

Está em PNG, vc não verá aqui, apenas se abrir a imagem.

![logos_ms-governo-federal-maio2016_branco](https://cloud.githubusercontent.com/assets/11232884/15650685/ce5f0640-2650-11e6-9ca8-1cedc1ef4ff6.png)

**Comment by rdemorais** [comment]
feito
